### PR TITLE
:bug:, :recycle: [cmd, demo] fix error on cmd help

### LINKED ISSUE #15: "./perun-eth-demo help" returns error
Running `./perun-eth-demo` lists `help` among the available commands, but running `./perun-eth-demo help` returns error `Error reading config file, open config.yaml: no such file or directory`.

### PR DESCRIPTION
**Pull request by matthiasgeihs**
- fixed error caused by trying to read config files when executing cli help
- moved demo command definition to package demo to allow for accessing cli variables

Fixes #15 

The problem was that when running the help command, it already tried to load the config files, where "config.yaml" is not present. My first idea was to load the config files only when running the demo command. However, for that I needed to make the config file parameters available to the package demo. Unfortunately, the demo command definition for some reason was in package cmd. To make it work, I refactored the demo command definition and its tests into package demo (where I think it belongs anyways).

### CODE REVIEW

**Comment by ggwpez** [comment]
If you resolve an issue with a MR, then use the *go-perun* naming scheme for the merge Branch (here: `15-help-error`) so we see to which issue a branch correlates.  
The `fix/*` notation is for stuff that does not have/need an issue.

**Comment by matthiasgeihs** [comment]
> If you resolve an issue with a MR, then use the _go-perun_ naming scheme for the merge Branch (here: `15-help-error`) so we see to which issue a branch correlates.
> The `fix/*` notation is for stuff that does not have/need an issue.

ok, so do you want me to rename the branch and create a new PR, or is it ok if i stick to the naming scheme next time?

**Comment by ggwpez** [comment]
> ok, so do you want me to rename the branch and create a new PR, or is it ok if i stick to the naming scheme next time?

It is fine for now, just so you know for the future :smile:

File: cmd/demo/demo.go [hunk 1]
```diff
@@ -25,21 +23,28 @@ var demoCmd = &cobra.Command{
 	Run: runDemo,
 }
 
-var testAPI bool
+var testAPIFlag bool
```
Comment (ggwpez) [inline cmd/demo/demo.go]: Maybe create another struct `demoConfig` which holds `testAPIEnabled` (rename from `testAPIFlag`), `cfgFile` and `cfgNetFile`. Just like the `logCfg` in `cmd/config.go`.

File: cmd/demo/demo.go [hunk 2]
```diff
@@ -25,21 +23,28 @@ var demoCmd = &cobra.Command{
...
-	demoCmd.PersistentFlags().StringVar(&demo.GetConfig().SecretKey, "sk", "", "ETH Secret Key")
+	demoCmd.PersistentFlags().StringVar(&cfgFile, "config", "config.yaml", "General config file")
+	demoCmd.PersistentFlags().StringVar(&cfgNetFile, "network", "network.yaml", "Network config file")
+	demoCmd.PersistentFlags().BoolVar(&testAPIFlag, "test-api", false, "Expose testing API at 8080")
+	demoCmd.PersistentFlags().BoolVar(&GetConfig().Node.PersistenceEnabled, "persistence", false, "Enables the persistence")
+	demoCmd.PersistentFlags().StringVar(&GetConfig().SecretKey, "sk", "", "ETH Secret Key")
 	viper.BindPFlag("secretkey", demoCmd.PersistentFlags().Lookup("sk"))
 }
 
+// GetDemoCmd exposes demoCmd so that it can be used as a sub-command by another cobra command instance
```
Comment (ggwpez) [inline cmd/demo/demo.go]:
```suggestion
// GetDemoCmd exposes demoCmd so that it can be used as a sub-command by another cobra command instance.
```

**Review by ggwpez — CHANGES_REQUESTED** [review]

File: cmd/root.go [hunk 3]
```diff
@@ -12,42 +12,27 @@ import (
...
-	Use:              "perun",
-	Short:            "Perun Network umbrella executable",
-	Long:             "Umbrella project for demonstrators and tests of the Perun Project.",
+	Use:              "perun-eth-demo",
+	Short:            "Perun State Channels Demo",
+	Long:             "Demonstrator for the Perun state channel framework using the Ethereum backend.",
 	PersistentPreRun: runRoot,
 }
 
 var cfgFile, cfgNetFile string
```
Comment (ggwpez) [inline cmd/root.go]:
```suggestion
```

File: cmd/demo/demo.go [hunk 4]
```diff
@@ -25,21 +23,28 @@ var demoCmd = &cobra.Command{
 	Run: runDemo,
 }
 
-var testAPI bool
+var testAPIFlag bool
+var cfgFile, cfgNetFile string
 
 func init() {
```
Comment (ggwpez) [inline cmd/demo/demo.go:35]: Thinking about it, we can probably put this whole function into `cmd/demo/Config.go`, (same for `root.go`) which would make it a bit easier to under stand since all the configuration is then in these two files.

File: cmd/demo/demo.go (hunk 2 above)
Comment (matthiasgeihs) [reply cmd/demo/demo.go]: done

File: cmd/demo/demo.go (hunk 1 above)
Comment (matthiasgeihs) [reply cmd/demo/demo.go]: ok, i created a struct for the command line flags.

File: cmd/root.go (hunk 3 above)
Comment (ggwpez) [reply cmd/root.go]: Why is this resolved?

Comment (matthiasgeihs) [reply cmd/root.go]: my bad, done now.

**Comment by ggwpez** [comment]
<s>It still fails for me when i do `go build . && perun-eth-demo help` on the `fix-command-help` branch…  </s>
PS: works

File: cmd/demo/demo.go (hunk 4 above)
Comment (ggwpez) [reply cmd/demo/demo.go:35]: You did not like this :rofl: ?

Comment (matthiasgeihs) [reply cmd/demo/demo.go:35]: by the whole function you mean `func init()`? i thought init fits well in file demo.go, as the package is also called "demo" and hence this is where you might expect the init function to be located. furthermore, since init initializes the command line flags, i thought it made sense to keep them within that same file. however, i don't care too much. both ways (keep in demo.go or move to config.go) are fine for me. you decide.

Comment (ggwpez) [reply cmd/demo/demo.go:35]: Then its ok.

**Review by ggwpez — CHANGES_REQUESTED** [review]
Ok looks great.  
Can you please squash 84b200516c310a015a728e03f496f5cbcd891bf0 and 7987932f734c4759ff40ffb9f63daf2c4867bf5d into something like ":recycle: Restructure config variables"?

**Comment by matthiasgeihs** [comment]
> Ok looks great.
> Can you please squash [84b2005](https://github.com/perun-network/perun-eth-demo/commit/84b200516c310a015a728e03f496f5cbcd891bf0) and [7987932](https://github.com/perun-network/perun-eth-demo/commit/7987932f734c4759ff40ffb9f63daf2c4867bf5d) into something like "♻️ Restructure config variables"?

squashed everything into one commit since [7987932](https://github.com/perun-network/perun-eth-demo/commit/7987932f734c4759ff40ffb9f63daf2c4867bf5d) was a fixup of the initial commit. ok?

**Review by ggwpez — APPROVED** [review]
