### PR TITLE
:sparkles: config option validate or deploy

### LINKED ISSUE #19: Error accepting channel proposal when running demo twice without restarting ganache-cli
### Problem:
The following error occurs when running the demo walkthrough twice without restarting ganache-cli:
> WARN[0007] error while funding channel: fund asset: sending funding tx: depositing asset 0: VM Exception while processing transaction: revert wrong amount of ETH for deposit  channel=68c440c697c7b65ab8b43da7f0a11e44362198818846f2a92b6cc66ed0bf021d id=0xA298Fc05bccff341f340a11FffA30567a00e651f
ERRO[0007] accepting channel proposal: error while funding channel: fund asset: sending funding tx: depositing asset 0: VM Exception while processing transaction: revert wrong amount of ETH for deposit

### Steps to reproduce:

1. Start ganache-cli
2. Start Alice and Bob nodes
3. Open channel and send ether from Alice to Bob
4. Close channel and shutdown Alice and Bob
5. Start Alice and Bob again (don't restart ganache-cli)
6. Open channel and send ether from Alice to Bob

### PR DESCRIPTION
**Pull request by matthiasgeihs**
Closes #19

### CODE REVIEW

File: cmd/demo/node_setup.go [hunk 1]
```diff
@@ -103,63 +105,125 @@ func (n *node) setup() error {
...
-		tmpAsset, err := strToAddress(config.Chain.Assetholder)
-		if err != nil {
-			return err
+	return ewallet.AsEthAddr(walletAddr), nil
+}
+
+func (n *node) setupAdjudicatorContract() error {
+	// config options: "[onChainAddress]", "deploy", "[onChainAddress]|deploy"
+
+	tokens := strings.Split(config.Chain.Adjudicator, "|")
```
Comment (ggwpez) [inline cmd/demo/node_setup.go]: If we use this config "hack", it should probably be parsed in the config setup (`cmd/demo.SetConfig`). I think it would be the cleanest to add two options to the `chainConfig` and then set them in `SetConfig`. Namely: `DeployAdjudicator` and `DeployAssetholder`, which can then be used in the functions here without having to parse the strings here. Same for the `setupAssetHolderContract`.  
  
Then please also fix the possible combinations when you parse the string, because right now `deploy|deploy|0x232…` would be valid.

File: cmd/demo/node_setup.go [hunk 2]
```diff
@@ -103,63 +105,125 @@ func (n *node) setup() error {
...
+			if adjAddr, err := stringToAddress(token); err == nil {
+				if err := n.validateAdjudicatorContract(adjAddr); err == nil {
+					n.adjAddr = adjAddr
+					n.adjudicatorSetup = true
+					fmt.Printf("✅ Adjudicator contract validated at %x\n", adjAddr)
+					return nil
+				}
+			}
+
+			fmt.Printf("❌ Adjudicator contract validation for %v failed\n", token)
```
Comment (ggwpez) [inline cmd/demo/node_setup.go]: Please always print the error messages if we have them, otherwise they are wasted.

File: cmd/demo/node_setup.go [hunk 3]
```diff
@@ -103,63 +105,125 @@ func (n *node) setup() error {
...
-		defer cancel()
-		if err := echannel.ValidateAssetHolderETH(ctx, n.cb, assAddr, adjAddr); err != nil {
-			return errors.WithMessage(err, "validating asset holder contract")
+	return errors.New("setup adjudicator contract")
+}
+
+func (n *node) setupAssetHolderContract() error {
+	// config options: "[onChainAddress]", "deploy", "[onChainAddress]|deploy"
+
+	if !n.adjudicatorSetup {
```
Comment (ggwpez) [inline cmd/demo/node_setup.go]: I think this kind of defensive programming makes it harder to read and does not add real value. Since this is an internal function, the usage can be assumed to be correct.

**Review by ggwpez — CHANGES_REQUESTED** [review]

File: cmd/demo/node_setup.go (hunk 1 above)
Comment (matthiasgeihs) [reply cmd/demo/node_setup.go]: > If we use this config "hack", it should probably be parsed in the config setup (`cmd/demo.SetConfig`). I think it would be the cleanest to add two options to the `chainConfig` and then set them in `SetConfig`. Namely: `DeployAdjudicator` and `DeployAssetholder`, which can then be used in the functions here without having to parse the strings here. Same for the `setupAssetHolderContract`.

Ok. How about just adding one config option`deployOnValidationFailure`, which means "if any contract validation fails, try to deploy the contract"? I don't see a case in the demo where one needs separate control over each contract deployment.

> Then please also fix the possible combinations when you parse the string, because right now `deploy|deploy|0x232…` would be valid.

This was actually intended, but becomes obsolete with your current suggestion.

**Comment by ggwpez** [comment]
As we discussed briefly today; It is probably better to have an extra option (eg. `deploy_on_missing_contracts`) which can then be set to `true` for *Alice* and `false` for *Bob*.  
@matthiasgeihs

File: cmd/demo/node_setup.go (hunk 2 above)
Comment (matthiasgeihs) [reply cmd/demo/node_setup.go]: not applicable to most recent version

**Comment by matthiasgeihs** [comment]
there is now an option `contractsetup` which can be one of `["validate", "deploy", "validateordeploy"]`. it defaults to "validateordeploy".

File: bob.yaml [hunk 4]
```diff
@@ -18,6 +18,7 @@ node:
 
 chain:
   url: ws://127.0.0.1:8545
+  contractsetup: validate
```
Comment (ggwpez) [inline bob.yaml:21]: What we just talked about:  
Either make it an `enum` and then parse the enum value in the `SetConfig` function (maybe `viper` can do enums?) 
or document and validate the possible string values, so that the user does not enter bogus.

Comment (matthiasgeihs) [reply bob.yaml:21]: as far as i could find out, viper does not support enums. i documented valid options in config.go. additionally i revised the setupContracts method to ensure that an expressive error is thrown if the option setupcontract is not specified correctly.

File: cmd/demo/node_setup.go (hunk 3 above)
Comment (matthiasgeihs) [reply cmd/demo/node_setup.go]: i removed the variable in the most recent version. (it became obsolete with the recent code revision. the point before was that if one does not know how to use the code correctly, the code would check that you cannot setup the asset holder without setting up the adjudicator.)

File: cmd/demo/node_setup.go (hunk 2 above)
Comment (matthiasgeihs) [reply cmd/demo/node_setup.go]: in the most recent version, the errors are returned to the calling function. is that sufficient? if not, could you give a concrete example how the error reporting should to be done?

**Comment by ggwpez** [comment]
Please fix the commits.

File: cmd/demo/node_setup.go [hunk 5]
```diff
@@ -109,63 +111,138 @@ func (n *node) setup() error {
 	return nil
 }
 
-// setupContracts reads from the config file whether the node should deploy or use
-// existing contract addresses.
-func (n *node) setupContracts() (err error) {
-	var adjAddr, assAddr common.Address
+func getTxContext() (context.Context, context.CancelFunc) {
```
Comment (ggwpez) [inline cmd/demo/node_setup.go]: We do not use `get*` prefix in golang.

Comment (matthiasgeihs) [reply cmd/demo/node_setup.go]: renamed to newTransactionContext

File: bob.yaml (hunk 4 above)
Comment (matthiasgeihs) [reply bob.yaml:21]: after offline discussion, now using separate type contractSetupOption and validating configuration during startup in config.go.

File: cmd/demo/node_setup.go [hunk 6]
```diff
@@ -109,63 +110,137 @@ func (n *node) setup() error {
...
-		if err != nil {
-			return err
-		}
-		adjAddr = ewallet.AsEthAddr(tmpAdj)
+func parseAndValidateAdjudicator(cb echannel.ContractBackend) (common.Address, error) {
+	var adjAddr common.Address
+	var err error
+
+	// parse address
+	adjAddr, err = stringToAddress(config.Chain.Adjudicator)
```
Comment (ggwpez) [inline cmd/demo/node_setup.go]: We should parse everything in the `SetConfig` functions, so that invalid user input makes the *demo* crash instantly and not in a command execution.

File: cmd/demo/node_setup.go [hunk 7]
```diff
@@ -109,63 +110,137 @@ func (n *node) setup() error {
...
-			return
-		}
-		fmt.Println("💭 Adjudicator contract deployed")
-	} else {
-		tmpAdj, err := strToAddress(config.Chain.Adjudicator)
-		if err != nil {
-			return err
-		}
-		adjAddr = ewallet.AsEthAddr(tmpAdj)
+func parseAndValidateAdjudicator(cb echannel.ContractBackend) (common.Address, error) {
```
Comment (ggwpez) [inline cmd/demo/node_setup.go]:
```suggestion
func validateAdjudicator(cb echannel.ContractBackend) (common.Address, error) {
```
If you do the suggestion below, we can change this to single-responsibility principle.

PS: The function becomes so short without the parsing that we probably do not need it anymore.

File: cmd/demo/node_setup.go [hunk 8]
```diff
@@ -109,63 +110,137 @@ func (n *node) setup() error {
...
-			return errors.WithMessage(err, "validating adjudicator contract")
-		}
+		err = echannel.ValidateAdjudicator(ctx, cb, adjAddr)
+	}
 
-		fmt.Println("💭 Adjudicator contract validated")
+	return adjAddr, err
+}
+
+func parseAndValidateAssetHolder(cb echannel.ContractBackend, adjAddr common.Address) (common.Address, error) {
```
Comment (ggwpez) [inline cmd/demo/node_setup.go]: Same here as with the `parseAndValidateAdjudicator` function.

File: cmd/demo/node_setup.go [hunk 9]
```diff
@@ -109,63 +110,137 @@ func (n *node) setup() error {
...
+		err = echannel.ValidateAssetHolderETH(ctx, cb, assAddr, adjAddr)
 	}
 
-	if config.Chain.Assetholder == "deploy" {
-		assAddr, err = deployAsset(n.cb, adjAddr)
-		if err != nil {
+	return assAddr, err
+}
+
+func stringToAddress(s string) (common.Address, error) {
```
Comment (ggwpez) [inline cmd/demo/node_setup.go]: If we do the parsing in the `config.go`, this function can also be moved there.

File: cmd/demo/node_setup.go [hunk 10]
```diff
@@ -109,63 +110,137 @@ func (n *node) setup() error {
...
+	if walletAddr, err = strToAddress(s); err != nil {
+		return common.Address{}, err
+	}
+
+	return ewallet.AsEthAddr(walletAddr), nil
+}
+
+func (n *node) setupContracts() error {
+	options := map[contractSetupOption]func() (common.Address, common.Address, error){
+		contractSetupOptionValidate: func() (adjAddr common.Address, assAddr common.Address, err error) {
```
Comment (ggwpez) [inline cmd/demo/node_setup.go]: These three functions look like code duplication, i think you can consolidate the two `Validate*` steps a bit.  
The map with the functions is not golang-style, you can just use a switch.

**Review by ggwpez — CHANGES_REQUESTED** [review]

File: cmd/demo/node_setup.go (hunk 6 above)
Comment (matthiasgeihs) [reply cmd/demo/node_setup.go]: done

File: cmd/demo/node_setup.go (hunk 7 above)
Comment (matthiasgeihs) [reply cmd/demo/node_setup.go]: done

File: cmd/demo/node_setup.go (hunk 8 above)
Comment (matthiasgeihs) [reply cmd/demo/node_setup.go]: done

File: cmd/demo/node_setup.go (hunk 9 above)
Comment (matthiasgeihs) [reply cmd/demo/node_setup.go]: done

File: cmd/demo/node_setup.go (hunk 10 above)
Comment (matthiasgeihs) [reply cmd/demo/node_setup.go]: not sure what you think can be consolidated. i refactored the code. especially moved the user notifications about validation and deployment to the sub functions. also replaced the map with switch.

File: cmd/demo/node_setup.go [hunk 11]
```diff
@@ -109,63 +109,74 @@ func (n *node) setup() error {
 	return nil
 }
 
-// setupContracts reads from the config file whether the node should deploy or use
-// existing contract addresses.
-func (n *node) setupContracts() (err error) {
-	var adjAddr, assAddr common.Address
+func newTransactionContext() (context.Context, context.CancelFunc) {
```
Comment (ggwpez) [inline cmd/demo/node_setup.go]: Please reorder the functions such that they are in order of importance.  eg:  
- setup
- setupPersistence
- setupContracts
- validateAdjudicator
- validateAssetHolder
- deployAdjudicator
- deployAssetHolder
- newTransactionContext

**Review by ggwpez — CHANGES_REQUESTED** [review]
Just one thing, looks good otherwise.  
PS: Please squash/fix the commits.

File: cmd/demo/node_setup.go (hunk 2 above)
Comment (ggwpez) [reply cmd/demo/node_setup.go]: Yes this is fine, just wanted to say that we should always use the error messages that we have.

File: cmd/demo/node_setup.go (hunk 11 above)
Comment (matthiasgeihs) [reply cmd/demo/node_setup.go]: ok, but changed order of setup persistence and setup contracts as setup contracts is called first.

**Review by ggwpez — APPROVED** [review]
